source "https://rubygems.org"
#-- For actual work
ruby '2.7.4'
gem 'sinatra'
gem 'shotgun'

#-- For checks
gem 'rspec'
gem 'pry'
gem 'rubocop'

#--No need but keep here not to forget
gem 'dotenv'
gem 'nokogiri'
gem 'open-uri'
gem 'json'
gem 'csv'
gem 'google_drive'
gem 'rexml'